ensembl_gtf: /nfs/users/nfs_k/ka8/scratch/annotations/GRCh38/genes/Ensembl_87/Homo_sapiens.GRCh38.87.gtf
reference_genome: /nfs/users/nfs_k/ka8/scratch/annotations/GRCh38/dna/Homo_sapiens.GRCh38.dna.primary_assembly.fa 
salmon_ensembl_index: /nfs/users/nfs_k/ka8/scratch/annotations/GRCh38/genes/Ensembl_87/salmon_index_87
star_index: /nfs/users/nfs_k/ka8/scratch/annotations/GRCh38/STAR_index_87
vcf_file: /nfs/users/nfs_k/ka8/scratch/projects/macrophage-gxe-study/genotypes/acLDL/hipsci.wec.gtarray.HumanCoreExome-12_v1_0.858samples.20141111.genotypes.GRCh38.sorted.filtered.vcf.gz
chromosome_lengths: /lustre/scratch117/cellgen/team170/ka8/annotations/GRCh38/bt2-index/chromosome_lengths.txt
samples: [AUIM_24h_AcLDL,AUIM_24h_Ctrl,BABK_24h_AcLDL,BABK_24h_Ctrl,BIMA_24h_AcLDL,BIMA_24h_Ctrl,BULB_24h_AcLDL,BULB_24h_Ctrl,CEHW_24h_AcLDL,CEHW_24h_Ctrl,COIO_24h_AcLDL,COIO_24h_Ctrl,DARW_24h_AcLDL,DARW_24h_Ctrl,DEBK_24h_AcLDL,DEBK_24h_Ctrl,EOFE_24h_AcLDL,EOFE_24h_Ctrl,EUIR_24h_AcLDL,EUIR_24h_Ctrl,GIUO_24h_AcLDL,GIUO_24h_Ctrl,GOMV_24h_AcLDL,GOMV_24h_Ctrl,JORR_24h_AcLDL,JORR_24h_Ctrl,KAKS_24h_AcLDL,KAKS_24h_Ctrl,MEQO_24h_AcLDL,MEQO_24h_Ctrl,OARZ_24h_AcLDL,OARZ_24h_Ctrl,RIIV_24h_AcLDL,RIIV_24h_Ctrl,VOAS_24h_AcLDL,VOAS_24h_Ctrl,ZUTA_24h_AcLDL,ZUTA_24h_Ctrl,XEGX_24h_AcLDL,XEGX_24h_Ctrl,VORX_24h_AcLDL,VORX_24h_Ctrl,BUBH_24h_AcLDL,BUBH_24h_Ctrl,CUPS_24h_AcLDL,CUPS_24h_Ctrl,OUGL_24h_AcLDL,OUGL_24h_Ctrl,EIKA_24h_AcLDL,EIKA_24h_Ctrl,IICQ_24h_AcLDL,IICQ_24h_Ctrl,NIBO_24h_AcLDL,NIBO_24h_Ctrl,NUSW_24h_AcLDL,NUSW_24h_Ctrl,PIUN_24h_AcLDL,PIUN_24h_Ctrl,UIMO_24h_AcLDL,UIMO_24h_Ctrl,UAHF_24h_Ctrl,UAHF_24h_AcLDL,IEKI_24h_Ctrl,IEKI_24h_AcLDL,CICB_24h_Ctrl,CICB_24h_AcLDL,OEFG_24h_Ctrl,OEFG_24h_AcLDL,RUYV_24h_Ctrl,RUYV_24h_AcLDL,VASS_24h_Ctrl,VASS_24h_AcLDL,YEMZ_24h_Ctrl,YEMZ_24h_AcLDL,EOJR_24h_Ctrl,EOJR_24h_AcLDL,IISA_24h_Ctrl,IISA_24h_AcLDL,JOXM_24h_Ctrl,JOXM_24h_AcLDL,PAHC_24h_Ctrl,PAHC_24h_AcLDL,SUKZ_24h_Ctrl,SUKZ_24h_AcLDL,VEQZ_24h_Ctrl,VEQZ_24h_AcLDL,XUCM_24h_Ctrl,XUCM_24h_AcLDL,MIJN_24h_Ctrl,MIJN_24h_AcLDL,BEZI_24h_AcLDL,BEZI_24h_Ctrl,EIPL_24h_AcLDL,EIPL_24h_Ctrl,FEBC_24h_AcLDL,FEBC_24h_Ctrl,HEJA_24h_AcLDL,HEJA_24h_Ctrl,HIAF_24h_AcLDL,HIAF_24h_Ctrl,KUXP_24h_AcLDL,KUXP_24h_Ctrl,NEMB_24h_AcLDL,NEMB_24h_Ctrl,OAPG_24h_AcLDL,OAPG_24h_Ctrl,PAMV_24h_AcLDL,PAMV_24h_Ctrl,PELM_24h_AcLDL,PELM_24h_Ctrl,PODX_24h_AcLDL,PODX_24h_Ctrl,XUGN_24h_AcLDL,XUGN_24h_Ctrl,OEVR_24h_Ctrl,OEVR_24h_AcLDL,FAFQ_24h_Ctrl,FAFQ_24h_AcLDL,HAYT_24h_Ctrl,HAYT_24h_AcLDL,IILL_24h_Ctrl,IILL_24h_AcLDL,SOJD_24h_Ctrl,SOJD_24h_AcLDL,DIKU_24h_Ctrl,DIKU_24h_AcLDL,GUSS_24h_Ctrl,GUSS_24h_AcLDL,QAQX_24h_Ctrl,QAQX_24h_AcLDL,ZAUI_24h_Ctrl,ZAUI_24h_AcLDL,EIWY_24h_Ctrl,EIWY_24h_AcLDL,NUKW_24h_Ctrl,NUKW_24h_AcLDL,NUKW_24h_LAL,NUKW_24h_LAL_AcLDL,FIKT_24h_Ctrl,FIKT_24h_AcLDL,FIKT_24h_LAL,FIKT_24h_LAL_AcLDL,COYI_24h_Ctrl,COYI_24h_AcLDL,COYI_24h_LAL,COYI_24h_LAL_AcLDL,HEHD_24h_Ctrl,HEHD_24h_AcLDL,HEHD_24h_LAL,HEHD_24h_LAL_AcLDL,QOLG_24h_Ctrl,QOLG_24h_AcLDL,QOLG_24h_LAL,QOLG_24h_LAL_AcLDL]
annotations: ["reviseAnnotations_contained","reviseAnnotations_downstream","reviseAnnotations_upstream"]
study: acLDL
libType: ISR

#Quantification
leafcutter_root: "/nfs/users/nfs_k/ka8/software/leafcutter"

#QTL mapping 
#conditions: ["Ctrl", "AcLDL", "Diff"]
conditions: ["Ctrl", "AcLDL"]
n_batches: 250
qtl_vcf: "/nfs/users/nfs_k/ka8/scratch/projects/macrophage-gxe-study/genotypes/acLDL/imputed_20151005/imputed.70_samples.sorted.filtered.named.INFO_07.vcf.gz"
#cis_window: 100000
cis_window: 500000
nominal_cis_window: 500000
annot_type: ["ensembl_87", "reviseAnnotations", "leafcutter", "featureCounts"]

#Colocalisation
coloc_phenotypes: ["ensembl_87", "reviseAnnotations", "leafcutter", "featureCounts"]
gwas_dir: "/nfs/users/nfs_k/ka8/scratch/datasets/Inflammatory_GWAS/"
coloc_window: 2e5
gwas_traits: ["AD","CEL_2010","CEL","CD","IBD","UC","MS","NAR","PBC","PS","RA_2012","RA","SCZ","SLE","T1D","T1D_2","T2D_1","T2D","UC_2012","UC_2014","CAD","MI","CRE","CRP","GLU","HDL","HGB","HOMA_b","HOMA_ir","IL6","INS","MCHC","MCH","MCV","PCV","PLT","RBC","TC","TG","UA","WBC","LDL","CAD_2017"]




